### ISSUE TITLE
Video port should be updated to art books

### ISSUE THREAD

**Issue by braxtonhall** [sunnypork/sunnypork.github.io#27]
- [x] Add instructions in the README for making changes to this page
- [x] Back button should close the modal

**Comment by braxtonhall** [comment]
The pdf here is larger than github's recommended maximum.

May want to consider either compressing or hosting elsewhere

**Comment by sunnypork** [comment]
![IMG_4218](https://user-images.githubusercontent.com/85819748/166838307-3907b45f-7d58-42c0-891e-43207de87eee.jpg)
![IMG_4217](https://user-images.githubusercontent.com/85819748/166838324-e410c918-1678-44ba-bf3c-166f1d9bbc72.jpg)
![IMG_4216](https://user-images.githubusercontent.com/85819748/166838329-6cf7c59c-c60b-4ccf-8101-f750670c992c.jpg)
![IMG_4215](https://user-images.githubusercontent.com/85819748/166838331-378e97aa-499d-4dc3-8c76-65077ac69a65.jpg)
![IMG_4214](https://user-images.githubusercontent.com/85819748/166838336-e2af12e8-f1ca-4de3-8336-5fb7b4d3f60d.jpg)
![IMG_4213](https://user-images.githubusercontent.com/85819748/166838339-6f3fb202-cd86-4e22-885c-ef66e43fdc2a.jpg)
